
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Tue Aug 27 20:34:00 CEST 2019
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int PP = 38;
  public static final int MM = 21;
  public static final int CONST = 22;
  public static final int GE = 28;
  public static final int NUMCONST = 42;
  public static final int CONTINUE = 36;
  public static final int LPAREN = 6;
  public static final int SEMI = 5;
  public static final int INTERFACE = 14;
  public static final int L = 19;
  public static final int FOR = 41;
  public static final int MINUS = 33;
  public static final int G = 32;
  public static final int RPAREN = 7;
  public static final int AND = 37;
  public static final int OR = 20;
  public static final int COMMA = 8;
  public static final int CLASS = 16;
  public static final int DIV = 27;
  public static final int EOL = 48;
  public static final int PLUS = 11;
  public static final int IF = 46;
  public static final int DOT = 15;
  public static final int LE = 23;
  public static final int EOF = 0;
  public static final int RETURN = 10;
  public static final int EQUAL = 12;
  public static final int NEW = 18;
  public static final int error = 1;
  public static final int DIF = 31;
  public static final int MOD = 24;
  public static final int IDENT = 45;
  public static final int BREAK = 17;
  public static final int VOID = 13;
  public static final int TIMES = 30;
  public static final int SAME = 35;
  public static final int ELSE = 47;
  public static final int LBRACE = 3;
  public static final int LSQUARE = 25;
  public static final int ENUM = 29;
  public static final int READ = 26;
  public static final int CHARCONST = 43;
  public static final int RSQUARE = 34;
  public static final int RBRACE = 4;
  public static final int BOOLCONST = 44;
  public static final int EXTENDS = 39;
  public static final int PROG = 2;
  public static final int IMPLEMENTS = 40;
  public static final int PRINT = 9;
}

